# Site wide configuration

title:            Weblog of JD
locale:           en_US
url: https://jatindhankhar.in


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#theme: minimal-mistakes-jekyll

remote_theme: "mmistakes/minimal-mistakes"

paginate: 5

defaults:
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      toc: true
      toc_label: Table
      breadcrumbs: true  # disabled by default


      
# Site owner
author:
  name: Jatin Dhankhar
  avatar: images/bio-photo.jpg
  bio: "Reader | Coder | Learner."
  email:
  disqus-shortname: weblogofjd
  twitter: jatindhankhar_
  facebook: #username
  google:
    plus: JatinDhankhar
    analytics: UA-50753070-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: jatindhankhar
  stackoverflow: 3455743/jatin-dhankhar
  keybase: jatin
  linkedin: jatindhankhar
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: jatindhankhar
  soundcloud: #username
  weibo: #username
  flickr: #username

search                   : true # true, false (default)
search_full_content      : true # true, false (default)

# Comments
comments:
  provider: disqus
  disqus:
    shortname: weblogofjd
include: [".htaccess"]
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp